#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀 Running pre-commit checks..."

pnpm lint

if [ $? -ne 0 ]; then
  echo "❌ Pre-commit checks failed. Push aborted."
  exit 1
fi

echo "✅ All checks passed. Proceeding with commit..."
